services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $authServiceUrl: '%auth.service_url%'
      $authClientId: '%auth.client_id%'
      $authClientSecret: '%auth.client_secret%'
      $authUrlAuthorize: '%auth.url_authorize%'
      $authUrlAccessToken: '%auth.url_access_token%'
      $authUrlResourcesOwnerDetails: '%auth.url_resources_owner_details%'
      $redirectUrl: '%auth.redirect_url%'

  Mixasmix\AuthBundle\Service\AuthService:
    public: true
    alias: 'auth_service'
